version: '3.8'
services:
  backend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.backend
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/frontend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
