"""user model email fix

Revision ID: 5fec0b39d1e2
Revises: a1adcef11937
Create Date: 2025-07-30 15:04:16.790445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fec0b39d1e2'
down_revision: Union[str, Sequence[str], None] = 'a1adcef11937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verification_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_code')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
